services:
  dev-backend:
    image: limehome/development
    build:
      context: .
      target: development
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
